  #配置服务器端口号
  server:
    port: 8080


  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root

      # 配置Redis------------------------------------------------------------------
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      #password: root
      timeout: 36000

    jpa:
      database: MYSQL
      show-sql: true
    jackson:
      serialization:
        write-dates-as-timestamps: true

      #图片大小限制
  servlet:
    multipart:
      max-file-size: 5MB

  mybatis-plus:
    type-aliases-package:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  logging:
    level:
      com.jeff.mapper: DEBUG

  #fastdfs设置
  fdfs:
    so-timeout: 5000       # 读取时间
    connect-timeout: 10000   # 连接超时时间
    thumb-image:           # 缩略图
      width: 100
      height: 100
    tracker-list:          # tracker服务配置地址列表
      - www.0622cc.cn:22122
  upload:
    base-url: www.0622cc.cn/
    allow-types:
      - image/jpeg
      - image/png
      - image/bmp
      - image/jpg
#---------------日志配置信息-------------------------------------------------------
  logging.level.root: info

